services:
  back:
    container_name: mercadona_back
    build: ./back
    restart: unless-stopped
    volumes:
      - ./back/logs:/app/logs
    ports:
      - "8089:80"
    secrets:
      - session_secret

  front:
    container_name: mercadona_front
    build: ./front
    restart: unless-stopped
    volumes:
      - ./front/logs:/logs
    ports:
      - "8088:80"

secrets:
  session_secret:
    file: ./back/secrets