services:
  back:
    container_name: mercadona_back
    build: ./back
    restart: unless-stopped
    volumes:
      - ./back/logs:/app/logs
    environment:
      - VIRTUAL_HOST=mercadona.iotcloud.es
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mercadona.iotcloud.es
      - VIRTUAL_PATH=/api/
      - VIRTUAL_DEST=/
    secrets:
      - session_secret

  front:
    container_name: mercadona_front
    build: ./front
    restart: unless-stopped
    volumes:
      - ./front/logs:/logs
    environment:
      - VIRTUAL_HOST=mercadona.iotcloud.es
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=mercadona.iotcloud.es
      - VIRTUAL_PATH=/

secrets:
  session_secret:
    file: ./back/secrets